(function(){
  'use strict';
  let formPrefix='service';
  const t=k=>HeerI18n.t(k), field=(name,label,type='text',required=true,extra='')=>`<div class="field ${extra.includes('full')?'full':''}"><label for="${formPrefix}-${name}">${t(label)}${required?' *':''}</label><input id="${formPrefix}-${name}" name="${name}" type="${type}" ${required?'required':''} ${extra.replace('full','')}><small class="error" aria-live="polite"></small></div>`;
  const select=(name,label,options,required=true)=>`<div class="field"><label for="${formPrefix}-${name}">${t(label)}${required?' *':''}</label><select id="${formPrefix}-${name}" name="${name}" ${required?'required':''}><option value="">${t('form.selectPlaceholder')}</option>${options.map(o=>`<option value="${o[0]}">${t(o[1])}</option>`).join('')}</select><small class="error" aria-live="polite"></small></div>`;
  const text=(name,label,required=false)=>`<div class="field full"><label for="${formPrefix}-${name}">${t(label)}${required?' *':''}</label><textarea id="${formPrefix}-${name}" name="${name}" ${required?'required':''}></textarea><small class="error" aria-live="polite"></small></div>`;
  const multi=(name,label,options)=>`<fieldset class="field full"><legend>${t(label)}</legend><div class="checkbox-group">${options.map(o=>`<label class="checkbox-label"><input type="checkbox" name="${name}" value="${o[0]}"> ${t(o[1])}</label>`).join('')}</div></fieldset>`;
  const common=()=>field('mobile','form.mobile','tel',true,'inputmode="numeric" pattern="[0-9]{10}" maxlength="10"')+field('email','form.email','email',false);
  const configs={
    pan:{title:'form.pan',html:()=>field('fullName','form.fullName')+common()+field('dob','form.dob','date')+select('serviceType','form.serviceType',[['New PAN','option.newPan'],['PAN Correction','option.panCorrection'],['PAN Update','option.panUpdate']])+select('applicantType','form.applicantType',[['Individual','form.individual'],['Business / Entity','form.entity'],['Other','form.otherOpt']])+text('notes','form.notes')},
    tan:{title:'form.tan',html:()=>field('businessName','form.businessName')+field('contactPerson','form.contactPerson')+common()+select('serviceType','form.serviceType',[['New TAN','option.newTan'],['TAN Correction','option.tanCorrection']])+field('businessType','form.businessType')+text('address','form.address',true)+text('notes','form.notes')},
    itr:{title:'form.itr',html:()=>field('fullName','form.fullName')+common()+field('year','form.year')+select('employment','form.employment',[['Salaried','form.salaried'],['Self-employed','form.self'],['Professional','form.professional'],['Business','form.business'],['Other','form.otherOpt']])+select('itrType','form.itrType',[['Not Sure','option.notSure'],['ITR-1','option.itr1'],['ITR-2','option.itr2'],['ITR-3','option.itr3'],['ITR-4','option.itr4']])+multi('income','form.income',[['Salary','form.salary'],['Business','form.business'],['Profession','form.profession'],['House Property','form.house'],['Capital Gains','form.capital'],['Other Sources','form.otherSources']])+select('existingPan','form.existingPan',[['Yes','form.yes'],['No','form.no']])+text('notes','form.notes')},
    gst:{title:'form.gst',html:()=>field('businessName','form.businessName')+common()+select('serviceType','form.serviceType',[['New GST Registration','option.newGst'],['GST Return Filing','option.gstReturn'],['GST Amendment / Update','option.gstAmend'],['GST Related Assistance','option.gstHelp']])+select('businessType','form.businessType',[['Proprietorship','form.proprietorship'],['Partnership','form.partnershipOpt'],['LLP','form.llpOpt'],['Company','form.companyOpt'],['Other','form.otherOpt']])+field('state','form.state')+text('businessAddress','form.businessAddress',true)+field('gstin','form.gstin','text',false)+text('notes','form.notes')},
    pf:{title:'form.pf',html:()=>field('company','form.company')+field('contactPerson','form.contactPerson')+common()+select('serviceType','form.serviceType',[['PF Registration','option.pfReg'],['PF Filing / Compliance','option.pfFiling'],['PF Assistance','option.pfHelp'],['Other','form.otherOpt']])+field('employees','form.employees','number',false,'min="0"')+text('notes','form.notes')},
    esi:{title:'form.esi',html:()=>field('company','form.company')+field('contactPerson','form.contactPerson')+common()+select('serviceType','form.serviceType',[['ESI Registration','option.esiReg'],['ESI Filing / Compliance','option.esiFiling'],['ESI Assistance','option.esiHelp'],['Other','form.otherOpt']])+field('employees','form.employees','number',false,'min="0"')+text('notes','form.notes')},
    llp:{title:'form.llp',html:()=>field('llpName','form.llpName')+field('applicant','form.applicant')+common()+field('partners','form.partners','number',true,'min="2"')+field('activity','form.activity')+field('city','form.city')+text('notes','form.notes')},
    partnership:{title:'form.partnership',html:()=>field('firmName','form.firmName')+field('applicant','form.applicant')+common()+field('partners','form.partners','number',true,'min="2"')+field('activity','form.activity')+field('city','form.city')+text('notes','form.notes')},
    other:{title:'form.other',html:()=>field('fullName','form.fullName')+common()+field('requiredService','form.requiredService')+text('description','form.description',true)+select('preferred','form.preferred',[['WhatsApp','form.wa'],['Call','form.call'],['Email','form.emailOpt']])}
  };
  function buildForms(){const host=document.querySelector('#dynamic-forms');if(!host)return;host.innerHTML=Object.entries(configs).map(([key,c],i)=>{formPrefix=key;return `<form class="form-card form-panel ${i===0?'active':''}" data-service-form="${key}" id="${key}-form" novalidate><h3>${t(c.title)}</h3><div class="success-message" role="status">${t('contact.success')}</div><div class="form-grid">${c.html()}</div><div class="upload-placeholder"><i class="bi bi-shield-lock"></i> ${t('aboutPage.upload')}</div><p class="form-note">${t('aboutPage.formDisclaimer')}</p><button class="btn btn-primary" type="submit">${t('aboutPage.submit')} <i class="bi bi-arrow-up-right"></i></button></form>`}).join('');
    document.querySelectorAll('[data-service-form]').forEach(bindForm);activateFromHash();}
  function labelFor(input){return input?.closest?.('.field')?.querySelector('label,legend')?.textContent.replace(' *','')||input?.name||'Field';}
  function validate(form){let ok=true;form.querySelectorAll('input,select,textarea').forEach(input=>{if(input.type==='checkbox')return;const err=input.closest('.field')?.querySelector('.error');let msg='';if(input.required&&!input.value.trim())msg=t('common.required');else if(input.type==='tel'&&input.value&&!/^[6-9]\d{9}$/.test(input.value.trim()))msg=t('common.invalidPhone');else if(input.type==='email'&&input.value&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(input.value.trim()))msg=t('common.invalidEmail');input.setAttribute('aria-invalid',String(!!msg));if(err)err.textContent=msg;if(msg)ok=false});return ok;}
  function bindForm(form){form.addEventListener('submit',async e=>{e.preventDefault();if(!validate(form)){form.querySelector('[aria-invalid="true"]')?.focus();return;}const data=new FormData(form),lines=[`Hello Heer Consultancy,`,``,`I would like assistance with ${t(configs[form.dataset.serviceForm]?.title||'common.services')}.`,` `];for(const [key,value] of data.entries()){if(value)lines.push(`${labelFor(form.querySelector(`[name="${CSS.escape(key)}"]`))}: ${value}`)}const success=form.querySelector('.success-message');if(HeerBusiness.CONFIG.formEndpoint){try{const response=await fetch(HeerBusiness.CONFIG.formEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(data))});if(!response.ok)throw new Error('Submission failed');success?.classList.add('show');form.reset();}catch(error){open(HeerBusiness.whatsapp(lines.join('\n')),'_blank','noopener');}}else{success?.classList.add('show');open(HeerBusiness.whatsapp(lines.join('\n')),'_blank','noopener');}});form.querySelectorAll('input,select,textarea').forEach(i=>i.addEventListener('blur',()=>{if(i.value)i.setAttribute('aria-invalid','false')}));}
  function activate(key,scroll=false){document.querySelectorAll('.form-tab').forEach(b=>{const on=b.dataset.form===key;b.classList.toggle('active',on);b.setAttribute('aria-selected',String(on))});document.querySelectorAll('.form-panel').forEach(f=>f.classList.toggle('active',f.dataset.serviceForm===key));if(scroll)document.querySelector('#apply')?.scrollIntoView({behavior:'smooth'});}
  function activateFromHash(){const key=location.hash.replace('#','').replace('-form','');if(configs[key])activate(key,true)}
  function bindContact(){document.querySelectorAll('.contact-form').forEach(form=>{if(form.dataset.bound)return;form.dataset.bound='true';bindForm(form);});}
  document.addEventListener('DOMContentLoaded',()=>{buildForms();bindContact();document.querySelectorAll('.form-tab').forEach(btn=>btn.addEventListener('click',()=>activate(btn.dataset.form)));addEventListener('hashchange',activateFromHash)});
  document.addEventListener('languagechange',()=>{buildForms();bindContact();document.querySelectorAll('.form-tab').forEach(btn=>btn.addEventListener('click',()=>activate(btn.dataset.form)));});
})();
