(function () {
  'use strict';
  const translations = {
    en: {
      common:{home:'Home',services:'Services',forms:'Forms',about:'About',why:'Why Us',process:'Process',faq:'FAQ',contact:'Contact',call:'Call Now',whatsapp:'Chat on WhatsApp',learn:'Learn More',apply:'Apply / Enquire',viewServices:'View Services',knowMore:'Know More',email:'Email Us',backHome:'Back to home',required:'This field is required.',invalidPhone:'Enter a valid 10-digit mobile number.',invalidEmail:'Enter a valid email address.',select:'Please select an option.',privacy:'Privacy Policy',terms:'Terms',close:'Close'},
      top:{call:'Call: 81600 83842',email:'hitesh12407@gmail.com',location:'Nava Naroda, Ahmedabad'},
      hero:{eyebrow:'Local assistance in Nava Naroda',title:'Reliable Tax & Documentation Services in Ahmedabad',subtitle:'PAN, ITR, GST, PF, ESI and business registration—all supported in one place with clear, convenient guidance.',note:'Clear communication • Convenient support • Local service',visualTitle:'Compliance overview',status:'Assistance ready',verified:'Document guidance',secure:'Secure handover guidance',followup:'Timely follow-up'},
      trust:{pan:'PAN Assistance',itr:'ITR Filing',gst:'GST Services',employee:'PF / ESI',business:'Business Registration'},
      services:{eyebrow:'What we help with',title:'Complete Tax & Documentation Services',intro:'Practical assistance for individuals, professionals and businesses across Ahmedabad.',all:'All Services',tax:'Tax Services',business:'Business Compliance',employee:'Employee Compliance',registration:'Registrations',docs:'Documentation'},
      downloads:{eyebrow:'Important Documents',title:'Download PAN & TAN Forms',intro:'Download commonly required PAN and TAN application and correction forms directly from Heer Consultancy.',document:'PDF Document',view:'View PDF',download:'Download',ctaTitle:"Can't find the form you need?",ctaText:'Contact Heer Consultancy for assistance with the correct PAN, TAN, tax or documentation form.',whatsapp:'WhatsApp Us',swipe:'Swipe to view all forms',downloadAria:'Download {title} PDF',viewAria:'View {title} PDF'},
      service:{pan:{title:'PAN Card Services',desc:'Assistance for new PAN applications, corrections and detail updates.',items:'New PAN|PAN Correction|PAN Update'},tan:{title:'TAN Services',desc:'Guidance for new TAN applications and correction requests.',items:'New TAN|TAN Correction'},itr:{title:'Income Tax Return Filing',desc:'ITR filing assistance based on your income profile and applicable form.',items:'ITR-1|ITR-2|ITR-3|ITR-4'},businessreturn:{title:'Business Return Filing',desc:'Organised return filing support for eligible businesses and professionals.',items:'Document review|Filing assistance'},gstreg:{title:'GST Registration',desc:'End-to-end application guidance for eligible businesses seeking GST registration.',items:'New registration|Amendment support'},gstreturn:{title:'GST Return Filing',desc:'Periodic GST return preparation and filing assistance for businesses.',items:'Return support|Compliance guidance'},pf:{title:'PF Services',desc:'Registration, filing and general PF compliance assistance for employers.',items:'PF Registration|PF Compliance'},esi:{title:'ESI Services',desc:'ESI registration and ongoing compliance assistance for establishments.',items:'ESI Registration|ESI Compliance'},llp:{title:'LLP Registration',desc:'Documentation and registration assistance for forming a Limited Liability Partnership.',items:'Name and document guidance|Application support'},partnership:{title:'Partnership Firm Registration',desc:'Practical support for partnership documentation and firm registration.',items:'Firm setup guidance|Documentation'},taxdocs:{title:'Tax & Government Documentation',desc:'Clear guidance for common tax and government documentation requirements.',items:'Application guidance|Document checklist'},businessdocs:{title:'Business Documentation Assistance',desc:'Support with business applications, records and related documentation.',items:'Business documents|Process assistance'}},
      aboutPreview:{eyebrow:'About Heer Consultancy',title:'Straightforward guidance for important paperwork',copy1:'Heer Consultancy provides convenient assistance for individuals, professionals and businesses seeking tax filing, registrations and government documentation services in Ahmedabad.',copy2:'Our approach is centred on clear requirements, organised document guidance and responsive communication from enquiry through completion.',quote:'Clarity at every step of your tax and documentation journey.',location:'Nava Naroda, Ahmedabad',i1:'Individual and business support',i2:'Clear document checklists',i3:'WhatsApp assistance',i4:'Local, accessible service'},
      why:{eyebrow:'Why choose us',title:'Support designed to keep things simple',intro:'A practical, communication-first approach to applications, filings and documentation.',fast:'Fast Process',fastText:'Prompt coordination and a clear next step for every enquiry.',docs:'Proper Document Guidance',docsText:'Know what is needed before the process begins.',wa:'Easy WhatsApp Assistance',waText:'Convenient updates and queries on a familiar channel.',both:'Individual & Business Services',bothText:'Support for personal filings and business compliance needs.',transparent:'Transparent Communication',transparentText:'Straightforward status updates without confusing language.',local:'Local Ahmedabad Assistance',localText:'Accessible service in Nava Naroda for nearby clients.'},
      process:{eyebrow:'How it works',title:'A simple four-step process',intro:'Start with a conversation. We will help you understand the relevant documents and next steps.',s1:'Contact Us',s1Text:'Call, WhatsApp or send an enquiry.',s2:'Share Required Documents',s2Text:'Receive a checklist and arrange a secure handover.',s3:'Verification & Processing',s3Text:'Details are reviewed and the service is processed.',s4:'Submission / Completion',s4Text:'Receive a clear update once the process is completed.'},
      categories:{eyebrow:'Service categories',title:'The right support for every requirement',tax:'Tax Services',taxText:'ITR and business return assistance',business:'Business Compliance',businessText:'GST registration and returns',employee:'Employee Compliance',employeeText:'PF and ESI services',reg:'Registrations',regText:'LLP, partnership and TAN',docs:'Government Documentation',docsText:'PAN and related assistance'},
      cta:{title:'Need Help With PAN, ITR, GST or Registration?',text:'Tell us what you need and we will guide you through the next steps.'},
      faq:{eyebrow:'Common questions',title:'Answers before you begin',intro:'Requirements can vary by case. Contact us for a checklist relevant to your service.',q1:'What documents are required for a PAN Card application?',a1:'Requirements depend on the application type and applicant. Commonly, identity, address and date-of-birth evidence may be needed. Contact us for the exact current checklist.',q2:'Can you help with PAN correction?',a2:'Yes. We assist with PAN correction and update requests, including guidance on the supporting documents required for the requested change.',q3:'Which ITR form should I file?',a3:'The applicable form depends on your income sources, status and other details. Share a brief profile and we can help identify the relevant filing route.',q4:'How can I register for GST?',a4:'We can guide you through eligibility, document preparation and the GST registration application process.',q5:'Do you provide GST return filing assistance?',a5:'Yes. GST return filing assistance is available for businesses that need periodic compliance support.',q6:'Do you assist with PF and ESI services?',a6:'Yes. Assistance is available for PF and ESI registration, filing and related compliance needs.',q7:'Can you help register an LLP or Partnership Firm?',a7:'Yes. We provide documentation and application assistance for LLP and partnership firm registrations.',q8:'How can I contact Heer Consultancy?',a8:'Call or WhatsApp us at 81600 83842, or email hitesh12407@gmail.com.',q9:'Where is Heer Consultancy located?',a9:'We are at Shop No. 35, Laxmivilla Greens, near Haridarshan Cross Road, Nava Naroda, Ahmedabad.',q10:'Can I send documents through WhatsApp?',a10:'You may use WhatsApp for initial coordination. Please avoid sending highly sensitive identity or financial documents until our team guides you on a suitable secure method.'},
      contact:{eyebrow:'Contact us',title:'Let’s discuss the service you need',intro:'Reach Heer Consultancy in Nava Naroda for tax, registration and government documentation assistance.',addressLabel:'Visit us',address:'Shop No. 35, Laxmivilla Greens, Near Haridarshan Cross Road, Nava Naroda, Ahmedabad, Gujarat, India.',phoneLabel:'Call or WhatsApp',emailLabel:'Email',hoursLabel:'Working hours',hours:'Contact us for current working hours',formTitle:'Send an enquiry',name:'Full Name',phone:'Mobile Number',email:'Email Address',service:'Service Required',message:'How can we help?',submit:'Continue on WhatsApp',success:'Thank you. WhatsApp is opening with your enquiry.',placeholderName:'Enter your full name',placeholderPhone:'10-digit mobile number',placeholderEmail:'name@example.com',placeholderMessage:'Tell us briefly what assistance you need',optPan:'PAN',optTan:'TAN',optItr:'ITR',optGstReg:'GST Registration',optGstReturn:'GST Return',optPf:'PF',optEsi:'ESI',optLlp:'LLP',optPartnership:'Partnership',optOther:'Other'},
      map:{title:'Visit Heer Consultancy',text:'Use the map for the Nava Naroda area. Confirm directions with us before visiting.',google:'Find Heer Consultancy on Google',googleText:'Google Business Profile link can be added when available.',directions:'Open area map'},
      footer:{desc:'Tax, registration and government documentation assistance for individuals and businesses in Ahmedabad.',quick:'Quick Links',services:'Services',contact:'Contact',rights:'Heer Consultancy. All rights reserved.',privacyText:'We use enquiry details only to respond to your request. Avoid sending sensitive identity or financial documents through unsecured channels.',termsText:'Website information is general service guidance. Requirements can vary by case and applicable rules.'},
      aboutPage:{crumb:'About',eyebrow:'Tax & documentation support',title:'About Heer Consultancy',intro:'Clear, convenient assistance for personal tax filings, business compliance and government documentation in Ahmedabad.',businessTitle:'Guidance that makes complex processes easier',businessP1:'Heer Consultancy supports individuals, professionals and businesses with tax filing, registrations, employee compliance and government documentation services.',businessP2:'From our Nava Naroda location, we focus on understanding the requirement, explaining the document checklist and keeping communication simple throughout the process.',mission:'Our Mission',missionText:'To simplify tax, compliance and government documentation services through clear guidance and convenient support.',who:'Who We Help',whoText:'Services are structured for a range of individual and business requirements.',individuals:'Individuals',salaried:'Salaried Professionals',self:'Self-employed Professionals',small:'Small Businesses',firms:'Partnership Firms',llps:'LLPs',owners:'Business Owners',overview:'Services Overview',overviewText:'One point of contact for routine tax, compliance, registration and documentation needs.',checkTitle:'Common Document Checklists',checkIntro:'Use these as an initial guide. Exact requirements are confirmed after understanding your case.',checkDisclaimer:'Required documents may vary depending on the applicant, service and applicable requirements. Please contact Heer Consultancy for the exact checklist.',applyEyebrow:'Start an enquiry',applyTitle:'Apply for a Service',applyIntro:'Choose a service, complete the relevant details and continue securely through WhatsApp.',formDisclaimer:'Please avoid submitting highly sensitive financial or identity documents through this form. Our team will guide you regarding secure document submission.',upload:'Document upload will become active once secure backend integration is configured.',submit:'Send via WhatsApp'},
      checklist:{pan:'PAN',panItems:'Identity proof|Address proof|Date-of-birth proof|Photograph/signature as applicable',tan:'TAN',tanItems:'Applicant or business details|Address details|Contact information|Supporting entity documents',itr:'ITR',itrItems:'PAN and contact details|Income details|Tax statements as applicable|Bank information as applicable',gst:'GST',gstItems:'Business constitution proof|Address proof|Authorised person details|Bank details as applicable',pf:'PF',pfItems:'Establishment details|Employee information|Business registration documents|Bank details as applicable',esi:'ESI',esiItems:'Establishment details|Employee information|Address and registration documents|Bank details as applicable',llp:'LLP',llpItems:'Proposed names|Partner identity/address proofs|Registered office proof|Business activity details',partnership:'Partnership',partnershipItems:'Proposed firm details|Partner identity/address proofs|Office address proof|Business activity details'},
      option:{newPan:'New PAN',panCorrection:'PAN Correction',panUpdate:'PAN Update',newTan:'New TAN',tanCorrection:'TAN Correction',notSure:'Not Sure',itr1:'ITR-1',itr2:'ITR-2',itr3:'ITR-3',itr4:'ITR-4',newGst:'New GST Registration',gstReturn:'GST Return Filing',gstAmend:'GST Amendment / Update',gstHelp:'GST Related Assistance',pfReg:'PF Registration',pfFiling:'PF Filing / Compliance',pfHelp:'PF Assistance',esiReg:'ESI Registration',esiFiling:'ESI Filing / Compliance',esiHelp:'ESI Assistance'},
      form:{pan:'PAN Services',tan:'TAN Services',itr:'ITR Filing',gst:'GST Services',pf:'PF Services',esi:'ESI Services',llp:'LLP Registration',partnership:'Partnership Firm',other:'Other Documentation',fullName:'Full Name',businessName:'Applicant / Business Name',company:'Company Name',contactPerson:'Contact Person',mobile:'Mobile Number',email:'Email Address',dob:'Date of Birth',serviceType:'Service Type',applicantType:'Applicant Type',notes:'Message / Notes',businessType:'Business Type',address:'Address',year:'Assessment Year / Financial Year',employment:'Employment Type',itrType:'ITR Type',income:'Income Sources',existingPan:'Existing PAN',state:'State',businessAddress:'Business Address',gstin:'GSTIN (if existing)',employees:'Number of Employees',llpName:'Proposed LLP Name',firmName:'Proposed Firm Name',applicant:'Applicant Name',partners:'Number of Partners',activity:'Business Activity',city:'City',requiredService:'Required Service',description:'Description',preferred:'Preferred Contact Method',notSure:'I am not sure which ITR applies to me',upload:'Document upload',selectPlaceholder:'Select an option',yes:'Yes',no:'No',individual:'Individual',entity:'Business / Entity',otherOpt:'Other',salaried:'Salaried',self:'Self-employed',professional:'Professional',business:'Business',proprietorship:'Proprietorship',partnershipOpt:'Partnership',llpOpt:'LLP',companyOpt:'Company',salary:'Salary',profession:'Profession',house:'House Property',capital:'Capital Gains',otherSources:'Other Sources',wa:'WhatsApp',call:'Call',emailOpt:'Email'}
    },
    gu: {
      common:{home:'હોમ',services:'સેવાઓ',forms:'ફોર્મ્સ',about:'અમારા વિશે',why:'અમને કેમ પસંદ કરશો?',process:'પ્રક્રિયા',faq:'FAQ',contact:'સંપર્ક',call:'હમણાં કૉલ કરો',whatsapp:'WhatsApp પર વાત કરો',learn:'વધુ જાણો',apply:'અરજી / પૂછપરછ',viewServices:'સેવાઓ જુઓ',knowMore:'વધુ જાણો',email:'ઈમેલ કરો',backHome:'હોમ પર પાછા જાઓ',required:'આ માહિતી જરૂરી છે.',invalidPhone:'માન્ય 10 અંકનો મોબાઇલ નંબર લખો.',invalidEmail:'માન્ય ઈમેલ સરનામું લખો.',select:'કૃપા કરીને વિકલ્પ પસંદ કરો.',privacy:'ગોપનીયતા નીતિ',terms:'શરતો',close:'બંધ કરો'},
      top:{call:'કૉલ: 81600 83842',email:'hitesh12407@gmail.com',location:'નવા નરોડા, અમદાવાદ'},
      hero:{eyebrow:'નવા નરોડામાં સ્થાનિક સહાય',title:'અમદાવાદમાં વિશ્વસનીય ટેક્સ અને ડોક્યુમેન્ટેશન સેવાઓ',subtitle:'PAN, ITR, GST, PF, ESI અને બિઝનેસ રજિસ્ટ્રેશન માટે સ્પષ્ટ અને સરળ માર્ગદર્શન એક જ સ્થળે.',note:'સ્પષ્ટ સંવાદ • સરળ સહાય • સ્થાનિક સેવા',visualTitle:'કમ્પ્લાયન્સની માહિતી',status:'સહાય માટે તૈયાર',verified:'ડોક્યુમેન્ટ માર્ગદર્શન',secure:'સુરક્ષિત હેન્ડઓવર માર્ગદર્શન',followup:'સમયસર ફોલોઅપ'},
      trust:{pan:'PAN સહાય',itr:'ITR ફાઇલિંગ',gst:'GST સેવાઓ',employee:'PF / ESI',business:'બિઝનેસ રજિસ્ટ્રેશન'},
      services:{eyebrow:'અમારી સહાય',title:'સંપૂર્ણ ટેક્સ અને ડોક્યુમેન્ટેશન સેવાઓ',intro:'અમદાવાદના વ્યક્તિઓ, પ્રોફેશનલ્સ અને બિઝનેસ માટે ઉપયોગી સહાય.',all:'બધી સેવાઓ',tax:'ટેક્સ સેવાઓ',business:'બિઝનેસ કમ્પ્લાયન્સ',employee:'કર્મચારી કમ્પ્લાયન્સ',registration:'રજિસ્ટ્રેશન',docs:'ડોક્યુમેન્ટેશન'},
      downloads:{eyebrow:'જરૂરી દસ્તાવેજો',title:'PAN અને TAN ફોર્મ ડાઉનલોડ કરો',intro:'Heer Consultancy પરથી જરૂરી PAN અને TAN અરજી તથા સુધારા ફોર્મ સરળતાથી ડાઉનલોડ કરો.',document:'PDF દસ્તાવેજ',view:'PDF જુઓ',download:'ડાઉનલોડ',ctaTitle:'તમને જરૂરી ફોર્મ મળ્યું નથી?',ctaText:'યોગ્ય PAN, TAN, Tax અથવા Documentation ફોર્મ માટે Heer Consultancyનો સંપર્ક કરો.',whatsapp:'WhatsApp પર સંપર્ક કરો',swipe:'બધા ફોર્મ જોવા માટે સ્વાઇપ કરો',downloadAria:'{title} PDF ડાઉનલોડ કરો',viewAria:'{title} PDF જુઓ'},
      service:{pan:{title:'PAN કાર્ડ સેવાઓ',desc:'નવા PAN, સુધારા અને માહિતી અપડેટ માટે સહાય.',items:'નવું PAN|PAN સુધારો|PAN અપડેટ'},tan:{title:'TAN સેવાઓ',desc:'નવા TAN અને સુધારા માટે માર્ગદર્શન.',items:'નવું TAN|TAN સુધારો'},itr:{title:'ઇન્કમ ટેક્સ રિટર્ન ફાઇલિંગ',desc:'આવકની વિગતો અનુસાર યોગ્ય ITR ફાઇલિંગ સહાય.',items:'ITR-1|ITR-2|ITR-3|ITR-4'},businessreturn:{title:'બિઝનેસ રિટર્ન ફાઇલિંગ',desc:'બિઝનેસ અને પ્રોફેશનલ્સ માટે વ્યવસ્થિત રિટર્ન સહાય.',items:'ડોક્યુમેન્ટ સમીક્ષા|ફાઇલિંગ સહાય'},gstreg:{title:'GST રજિસ્ટ્રેશન',desc:'પાત્ર બિઝનેસ માટે GST રજિસ્ટ્રેશન અરજી માર્ગદર્શન.',items:'નવું રજિસ્ટ્રેશન|સુધારા સહાય'},gstreturn:{title:'GST રિટર્ન ફાઇલિંગ',desc:'બિઝનેસ માટે નિયમિત GST રિટર્ન ફાઇલિંગ સહાય.',items:'રિટર્ન સહાય|કમ્પ્લાયન્સ માર્ગદર્શન'},pf:{title:'PF સેવાઓ',desc:'નિયોક્તાઓ માટે PF રજિસ્ટ્રેશન અને કમ્પ્લાયન્સ સહાય.',items:'PF રજિસ્ટ્રેશન|PF કમ્પ્લાયન્સ'},esi:{title:'ESI સેવાઓ',desc:'સ્થાપનાઓ માટે ESI રજિસ્ટ્રેશન અને કમ્પ્લાયન્સ સહાય.',items:'ESI રજિસ્ટ્રેશન|ESI કમ્પ્લાયન્સ'},llp:{title:'LLP રજિસ્ટ્રેશન',desc:'લિમિટેડ લાયબિલિટી પાર્ટનરશિપ માટે ડોક્યુમેન્ટ અને અરજી સહાય.',items:'નામ અને ડોક્યુમેન્ટ માર્ગદર્શન|અરજી સહાય'},partnership:{title:'પાર્ટનરશિપ ફર્મ રજિસ્ટ્રેશન',desc:'પાર્ટનરશિપ ડોક્યુમેન્ટેશન અને ફર્મ રજિસ્ટ્રેશનમાં સહાય.',items:'ફર્મ સ્થાપના માર્ગદર્શન|ડોક્યુમેન્ટેશન'},taxdocs:{title:'ટેક્સ અને સરકારી ડોક્યુમેન્ટેશન',desc:'ટેક્સ અને સરકારી ડોક્યુમેન્ટ સંબંધિત સ્પષ્ટ માર્ગદર્શન.',items:'અરજી માર્ગદર્શન|ડોક્યુમેન્ટ ચેકલિસ્ટ'},businessdocs:{title:'બિઝનેસ ડોક્યુમેન્ટેશન સહાય',desc:'બિઝનેસ અરજી, રેકોર્ડ અને સંબંધિત ડોક્યુમેન્ટમાં સહાય.',items:'બિઝનેસ ડોક્યુમેન્ટ|પ્રક્રિયા સહાય'}},
      aboutPreview:{eyebrow:'હીર કન્સલ્ટન્સી વિશે',title:'મહત્વપૂર્ણ દસ્તાવેજી કામ માટે સરળ માર્ગદર્શન',copy1:'હીર કન્સલ્ટન્સી અમદાવાદમાં વ્યક્તિઓ, પ્રોફેશનલ્સ અને બિઝનેસને ટેક્સ ફાઇલિંગ, રજિસ્ટ્રેશન અને સરકારી ડોક્યુમેન્ટેશન માટે સહાય આપે છે.',copy2:'અમારો અભિગમ સ્પષ્ટ જરૂરિયાતો, વ્યવસ્થિત ડોક્યુમેન્ટ માર્ગદર્શન અને સમયસર સંવાદ પર આધારિત છે.',quote:'તમારી ટેક્સ અને ડોક્યુમેન્ટેશન પ્રક્રિયાના દરેક પગલે સ્પષ્ટતા.',location:'નવા નરોડા, અમદાવાદ',i1:'વ્યક્તિ અને બિઝનેસ સહાય',i2:'સ્પષ્ટ ડોક્યુમેન્ટ ચેકલિસ્ટ',i3:'WhatsApp સહાય',i4:'સ્થાનિક અને સરળ સેવા'},
      why:{eyebrow:'અમને કેમ પસંદ કરશો?',title:'તમારા માટે પ્રક્રિયા સરળ બનાવતી સહાય',intro:'અરજી, ફાઇલિંગ અને ડોક્યુમેન્ટેશન માટે સરળ અને સંવાદ આધારિત અભિગમ.',fast:'ઝડપી પ્રક્રિયા',fastText:'દરેક પૂછપરછ માટે સમયસર સંકલન અને સ્પષ્ટ આગળનું પગલું.',docs:'યોગ્ય ડોક્યુમેન્ટ માર્ગદર્શન',docsText:'પ્રક્રિયા શરૂ કરતા પહેલાં જરૂરી માહિતી મેળવો.',wa:'સરળ WhatsApp સહાય',waText:'પરિચિત માધ્યમ પર સરળ અપડેટ અને પ્રશ્નોત્તરી.',both:'વ્યક્તિ અને બિઝનેસ સેવાઓ',bothText:'વ્યક્તિગત ફાઇલિંગ અને બિઝનેસ કમ્પ્લાયન્સ માટે સહાય.',transparent:'પારદર્શક સંવાદ',transparentText:'અઘરી ભાષા વિના સીધી અને સ્પષ્ટ માહિતી.',local:'અમદાવાદમાં સ્થાનિક સહાય',localText:'નજીકના ગ્રાહકો માટે નવા નરોડામાં સુલભ સેવા.'},
      process:{eyebrow:'પ્રક્રિયા',title:'સરળ ચાર પગલાંની પ્રક્રિયા',intro:'વાતચીતથી શરૂઆત કરો. અમે જરૂરી ડોક્યુમેન્ટ અને આગળના પગલાં સમજાવીશું.',s1:'અમારો સંપર્ક કરો',s1Text:'કૉલ, WhatsApp અથવા પૂછપરછ મોકલો.',s2:'જરૂરી ડોક્યુમેન્ટ આપો',s2Text:'ચેકલિસ્ટ મેળવો અને સુરક્ષિત રીતે ડોક્યુમેન્ટ આપો.',s3:'ચકાસણી અને પ્રક્રિયા',s3Text:'વિગતોની ચકાસણી પછી સેવા પ્રક્રિયા આગળ વધે છે.',s4:'સબમિશન / પૂર્ણતા',s4Text:'પ્રક્રિયા પૂર્ણ થાય ત્યારે સ્પષ્ટ અપડેટ મેળવો.'},
      categories:{eyebrow:'સેવા કેટેગરી',title:'દરેક જરૂરિયાત માટે યોગ્ય સહાય',tax:'ટેક્સ સેવાઓ',taxText:'ITR અને બિઝનેસ રિટર્ન સહાય',business:'બિઝનેસ કમ્પ્લાયન્સ',businessText:'GST રજિસ્ટ્રેશન અને રિટર્ન',employee:'કર્મચારી કમ્પ્લાયન્સ',employeeText:'PF અને ESI સેવાઓ',reg:'રજિસ્ટ્રેશન',regText:'LLP, પાર્ટનરશિપ અને TAN',docs:'સરકારી ડોક્યુમેન્ટેશન',docsText:'PAN અને સંબંધિત સહાય'},
      cta:{title:'PAN, ITR, GST અથવા રજિસ્ટ્રેશનમાં મદદ જોઈએ છે?',text:'તમારી જરૂરિયાત જણાવો અને અમે આગળના પગલાંનું માર્ગદર્શન આપીશું.'},
      faq:{eyebrow:'સામાન્ય પ્રશ્નો',title:'શરૂઆત પહેલાં ઉપયોગી જવાબો',intro:'જરૂરિયાત કેસ પ્રમાણે બદલાઈ શકે છે. યોગ્ય ચેકલિસ્ટ માટે અમારો સંપર્ક કરો.',q1:'PAN કાર્ડ અરજી માટે કયા ડોક્યુમેન્ટ જોઈએ?',a1:'અરજી અને અરજદારના પ્રકાર પ્રમાણે જરૂરિયાત બદલાય છે. સામાન્ય રીતે ઓળખ, સરનામું અને જન્મતારીખના પુરાવા જરૂરી હોઈ શકે છે. ચોક્કસ ચેકલિસ્ટ માટે સંપર્ક કરો.',q2:'શું તમે PAN સુધારામાં મદદ કરો છો?',a2:'હા. જરૂરી ફેરફાર માટે આધારરૂપ ડોક્યુમેન્ટના માર્ગદર્શન સાથે PAN સુધારા અને અપડેટમાં મદદ કરીએ છીએ.',q3:'મારે કયું ITR ફોર્મ ભરવું જોઈએ?',a3:'યોગ્ય ફોર્મ તમારી આવકના સ્ત્રોત અને અન્ય વિગતો પર આધારિત છે. સંક્ષિપ્ત માહિતી આપો અને અમે યોગ્ય માર્ગ સમજાવવામાં મદદ કરીશું.',q4:'GST રજિસ્ટ્રેશન કેવી રીતે કરવું?',a4:'પાત્રતા, ડોક્યુમેન્ટ તૈયારી અને GST રજિસ્ટ્રેશન અરજી પ્રક્રિયામાં અમે માર્ગદર્શન આપીએ છીએ.',q5:'શું GST રિટર્ન ફાઇલિંગની સહાય મળે છે?',a5:'હા. નિયમિત કમ્પ્લાયન્સની જરૂર ધરાવતા બિઝનેસ માટે GST રિટર્ન ફાઇલિંગ સહાય ઉપલબ્ધ છે.',q6:'શું PF અને ESI સેવાઓ આપો છો?',a6:'હા. PF અને ESI રજિસ્ટ્રેશન, ફાઇલિંગ અને સંબંધિત કમ્પ્લાયન્સ માટે સહાય ઉપલબ્ધ છે.',q7:'LLP અથવા પાર્ટનરશિપ ફર્મ રજિસ્ટર કરવામાં મદદ મળે છે?',a7:'હા. LLP અને પાર્ટનરશિપ ફર્મ રજિસ્ટ્રેશન માટે ડોક્યુમેન્ટેશન અને અરજી સહાય આપીએ છીએ.',q8:'હીર કન્સલ્ટન્સીનો સંપર્ક કેવી રીતે કરવો?',a8:'81600 83842 પર કૉલ અથવા WhatsApp કરો અથવા hitesh12407@gmail.com પર ઈમેલ કરો.',q9:'હીર કન્સલ્ટન્સી ક્યાં આવેલી છે?',a9:'શોપ નં. 35, લક્ષ્મીવિલા ગ્રીન્સ, હરિદર્શન ક્રોસ રોડ પાસે, નવા નરોડા, અમદાવાદ.',q10:'શું WhatsApp પર ડોક્યુમેન્ટ મોકલી શકું?',a10:'પ્રાથમિક વાતચીત માટે WhatsApp વાપરી શકો છો. ખૂબ સંવેદનશીલ ઓળખ અથવા નાણાકીય ડોક્યુમેન્ટ મોકલતા પહેલાં અમારી ટીમ પાસેથી સુરક્ષિત પદ્ધતિનું માર્ગદર્શન લો.'},
      contact:{eyebrow:'અમારો સંપર્ક કરો',title:'તમારે કઈ સેવા જોઈએ છે તે જણાવો',intro:'ટેક્સ, રજિસ્ટ્રેશન અને સરકારી ડોક્યુમેન્ટેશન સહાય માટે નવા નરોડાની હીર કન્સલ્ટન્સીનો સંપર્ક કરો.',addressLabel:'મુલાકાત લો',address:'શોપ નં. 35, લક્ષ્મીવિલા ગ્રીન્સ, હરિદર્શન ક્રોસ રોડ પાસે, નવા નરોડા, અમદાવાદ, ગુજરાત, ભારત.',phoneLabel:'કૉલ અથવા WhatsApp',emailLabel:'ઈમેલ',hoursLabel:'કામકાજનો સમય',hours:'વર્તમાન સમય માટે અમારો સંપર્ક કરો',formTitle:'પૂછપરછ મોકલો',name:'પૂરું નામ',phone:'મોબાઇલ નંબર',email:'ઈમેલ સરનામું',service:'જરૂરી સેવા',message:'અમે કેવી રીતે મદદ કરી શકીએ?',submit:'WhatsApp પર આગળ વધો',success:'આભાર. તમારી પૂછપરછ સાથે WhatsApp ખુલી રહ્યું છે.',placeholderName:'તમારું પૂરું નામ લખો',placeholderPhone:'10 અંકનો મોબાઇલ નંબર',placeholderEmail:'name@example.com',placeholderMessage:'તમારી જરૂરિયાત ટૂંકમાં જણાવો',optPan:'PAN',optTan:'TAN',optItr:'ITR',optGstReg:'GST રજિસ્ટ્રેશન',optGstReturn:'GST રિટર્ન',optPf:'PF',optEsi:'ESI',optLlp:'LLP',optPartnership:'પાર્ટનરશિપ',optOther:'અન્ય'},
      map:{title:'હીર કન્સલ્ટન્સીની મુલાકાત લો',text:'નવા નરોડા વિસ્તાર માટે નકશો જુઓ. મુલાકાત પહેલાં દિશા માટે અમારો સંપર્ક કરો.',google:'Google પર હીર કન્સલ્ટન્સી શોધો',googleText:'Google Business Profileની લિંક ઉપલબ્ધ થયા પછી ઉમેરી શકાય છે.',directions:'વિસ્તારનો નકશો ખોલો'},
      footer:{desc:'અમદાવાદના વ્યક્તિઓ અને બિઝનેસ માટે ટેક્સ, રજિસ્ટ્રેશન અને સરકારી ડોક્યુમેન્ટેશન સહાય.',quick:'ઝડપી લિંક્સ',services:'સેવાઓ',contact:'સંપર્ક',rights:'હીર કન્સલ્ટન્સી. સર્વ હક્ક સુરક્ષિત.',privacyText:'પૂછપરછની વિગતોનો ઉપયોગ માત્ર જવાબ આપવા માટે થાય છે. અસુરક્ષિત માધ્યમથી સંવેદનશીલ ઓળખ કે નાણાકીય ડોક્યુમેન્ટ મોકલશો નહીં.',termsText:'વેબસાઇટની માહિતી સામાન્ય સેવા માર્ગદર્શન છે. કેસ અને લાગુ નિયમો પ્રમાણે જરૂરિયાત બદલાઈ શકે છે.'},
      aboutPage:{crumb:'અમારા વિશે',eyebrow:'ટેક્સ અને ડોક્યુમેન્ટેશન સહાય',title:'હીર કન્સલ્ટન્સી વિશે',intro:'અમદાવાદમાં વ્યક્તિગત ટેક્સ ફાઇલિંગ, બિઝનેસ કમ્પ્લાયન્સ અને સરકારી ડોક્યુમેન્ટેશન માટે સ્પષ્ટ અને સરળ સહાય.',businessTitle:'જટિલ પ્રક્રિયાને સરળ બનાવતું માર્ગદર્શન',businessP1:'હીર કન્સલ્ટન્સી વ્યક્તિઓ, પ્રોફેશનલ્સ અને બિઝનેસને ટેક્સ ફાઇલિંગ, રજિસ્ટ્રેશન, કર્મચારી કમ્પ્લાયન્સ અને સરકારી ડોક્યુમેન્ટેશન સેવાઓમાં સહાય કરે છે.',businessP2:'નવા નરોડાથી અમે જરૂરિયાત સમજવા, ડોક્યુમેન્ટ ચેકલિસ્ટ સમજાવવા અને સમગ્ર પ્રક્રિયામાં સરળ સંવાદ પર ધ્યાન આપીએ છીએ.',mission:'અમારું મિશન',missionText:'સ્પષ્ટ માર્ગદર્શન અને સરળ સહાય દ્વારા ટેક્સ, કમ્પ્લાયન્સ અને સરકારી ડોક્યુમેન્ટેશન સેવાઓને સરળ બનાવવી.',who:'અમે કોને મદદ કરીએ છીએ',whoText:'વિવિધ વ્યક્તિગત અને બિઝનેસ જરૂરિયાતો માટે સેવાઓ ઉપલબ્ધ છે.',individuals:'વ્યક્તિઓ',salaried:'પગારદાર પ્રોફેશનલ્સ',self:'સ્વરોજગાર પ્રોફેશનલ્સ',small:'નાના બિઝનેસ',firms:'પાર્ટનરશિપ ફર્મ',llps:'LLP',owners:'બિઝનેસ માલિકો',overview:'સેવાઓનો પરિચય',overviewText:'ટેક્સ, કમ્પ્લાયન્સ, રજિસ્ટ્રેશન અને ડોક્યુમેન્ટેશન માટે એક સંપર્ક સ્થળ.',checkTitle:'સામાન્ય ડોક્યુમેન્ટ ચેકલિસ્ટ',checkIntro:'પ્રાથમિક માર્ગદર્શન માટે આ યાદી જુઓ. તમારી વિગતો સમજ્યા પછી ચોક્કસ જરૂરિયાત જણાવવામાં આવશે.',checkDisclaimer:'જરૂરી ડોક્યુમેન્ટ અરજદાર, સેવા અને લાગુ પડતી જરૂરિયાતો પ્રમાણે બદલાઈ શકે છે. ચોક્કસ ચેકલિસ્ટ માટે હીર કન્સલ્ટન્સીનો સંપર્ક કરો.',applyEyebrow:'પૂછપરછ શરૂ કરો',applyTitle:'સેવા માટે અરજી કરો',applyIntro:'સેવા પસંદ કરો, જરૂરી વિગતો ભરો અને WhatsApp દ્વારા આગળ વધો.',formDisclaimer:'આ ફોર્મ દ્વારા અત્યંત સંવેદનશીલ નાણાકીય અથવા ઓળખના ડોક્યુમેન્ટ મોકલશો નહીં. સુરક્ષિત ડોક્યુમેન્ટ સબમિશન માટે અમારી ટીમ માર્ગદર્શન આપશે.',upload:'સુરક્ષિત બેકએન્ડ ગોઠવાયા પછી ડોક્યુમેન્ટ અપલોડ સક્રિય થશે.',submit:'WhatsApp દ્વારા મોકલો'},
      checklist:{pan:'PAN',panItems:'ઓળખનો પુરાવો|સરનામાનો પુરાવો|જન્મતારીખનો પુરાવો|લાગુ પડે તેમ ફોટો/સહી',tan:'TAN',tanItems:'અરજદાર અથવા બિઝનેસની વિગતો|સરનામાની વિગતો|સંપર્ક માહિતી|એન્ટિટીના આધારરૂપ ડોક્યુમેન્ટ',itr:'ITR',itrItems:'PAN અને સંપર્ક વિગતો|આવકની વિગતો|લાગુ પડતા ટેક્સ સ્ટેટમેન્ટ|લાગુ પડતી બેંક માહિતી',gst:'GST',gstItems:'બિઝનેસ બંધારણનો પુરાવો|સરનામાનો પુરાવો|અધિકૃત વ્યક્તિની વિગતો|લાગુ પડતી બેંક વિગતો',pf:'PF',pfItems:'સ્થાપનાની વિગતો|કર્મચારી માહિતી|બિઝનેસ રજિસ્ટ્રેશન ડોક્યુમેન્ટ|લાગુ પડતી બેંક વિગતો',esi:'ESI',esiItems:'સ્થાપનાની વિગતો|કર્મચારી માહિતી|સરનામા અને રજિસ્ટ્રેશન ડોક્યુમેન્ટ|લાગુ પડતી બેંક વિગતો',llp:'LLP',llpItems:'સૂચિત નામ|પાર્ટનરની ઓળખ/સરનામાના પુરાવા|રજિસ્ટર્ડ ઓફિસનો પુરાવો|બિઝનેસ પ્રવૃત્તિની વિગતો',partnership:'પાર્ટનરશિપ',partnershipItems:'સૂચિત ફર્મની વિગતો|પાર્ટનરની ઓળખ/સરનામાના પુરાવા|ઓફિસ સરનામાનો પુરાવો|બિઝનેસ પ્રવૃત્તિની વિગતો'},
      option:{newPan:'નવું PAN',panCorrection:'PAN સુધારો',panUpdate:'PAN અપડેટ',newTan:'નવું TAN',tanCorrection:'TAN સુધારો',notSure:'ખાતરી નથી',itr1:'ITR-1',itr2:'ITR-2',itr3:'ITR-3',itr4:'ITR-4',newGst:'નવું GST રજિસ્ટ્રેશન',gstReturn:'GST રિટર્ન ફાઇલિંગ',gstAmend:'GST સુધારો / અપડેટ',gstHelp:'GST સંબંધિત સહાય',pfReg:'PF રજિસ્ટ્રેશન',pfFiling:'PF ફાઇલિંગ / કમ્પ્લાયન્સ',pfHelp:'PF સહાય',esiReg:'ESI રજિસ્ટ્રેશન',esiFiling:'ESI ફાઇલિંગ / કમ્પ્લાયન્સ',esiHelp:'ESI સહાય'},
      form:{pan:'PAN સેવાઓ',tan:'TAN સેવાઓ',itr:'ITR ફાઇલિંગ',gst:'GST સેવાઓ',pf:'PF સેવાઓ',esi:'ESI સેવાઓ',llp:'LLP રજિસ્ટ્રેશન',partnership:'પાર્ટનરશિપ ફર્મ',other:'અન્ય ડોક્યુમેન્ટેશન',fullName:'પૂરું નામ',businessName:'અરજદાર / બિઝનેસનું નામ',company:'કંપનીનું નામ',contactPerson:'સંપર્ક વ્યક્તિ',mobile:'મોબાઇલ નંબર',email:'ઈમેલ સરનામું',dob:'જન્મ તારીખ',serviceType:'સેવાનો પ્રકાર',applicantType:'અરજદારનો પ્રકાર',notes:'સંદેશ / નોંધ',businessType:'બિઝનેસનો પ્રકાર',address:'સરનામું',year:'એસેસમેન્ટ વર્ષ / નાણાકીય વર્ષ',employment:'રોજગારનો પ્રકાર',itrType:'ITR પ્રકાર',income:'આવકના સ્ત્રોત',existingPan:'PAN ઉપલબ્ધ છે?',state:'રાજ્ય',businessAddress:'બિઝનેસ સરનામું',gstin:'GSTIN (જો હોય તો)',employees:'કર્મચારીઓની સંખ્યા',llpName:'સૂચિત LLP નામ',firmName:'સૂચિત ફર્મનું નામ',applicant:'અરજદારનું નામ',partners:'પાર્ટનરની સંખ્યા',activity:'બિઝનેસ પ્રવૃત્તિ',city:'શહેર',requiredService:'જરૂરી સેવા',description:'વિગત',preferred:'પસંદગીની સંપર્ક પદ્ધતિ',notSure:'મને કયું ITR લાગુ પડે છે તેની ખાતરી નથી',upload:'ડોક્યુમેન્ટ અપલોડ',selectPlaceholder:'વિકલ્પ પસંદ કરો',yes:'હા',no:'ના',individual:'વ્યક્તિ',entity:'બિઝનેસ / એન્ટિટી',otherOpt:'અન્ય',salaried:'પગારદાર',self:'સ્વરોજગાર',professional:'પ્રોફેશનલ',business:'બિઝનેસ',proprietorship:'પ્રોપ્રાઇટરશિપ',partnershipOpt:'પાર્ટનરશિપ',llpOpt:'LLP',companyOpt:'કંપની',salary:'પગાર',profession:'પ્રોફેશન',house:'હાઉસ પ્રોપર્ટી',capital:'કેપિટલ ગેઇન',otherSources:'અન્ય સ્ત્રોત',wa:'WhatsApp',call:'કૉલ',emailOpt:'ઈમેલ'}
    }
  };

  const get = (obj, path) => path.split('.').reduce((acc, key) => acc && acc[key], obj);
  function currentLanguage(){ return localStorage.getItem('heer-language') === 'gu' ? 'gu' : 'en'; }
  function t(key, lang){ return get(translations[lang || currentLanguage()], key) || get(translations.en, key) || key; }
  function applyTranslations(lang){
    document.documentElement.lang = lang;
    document.querySelectorAll('[data-i18n]').forEach(el => { const value=t(el.dataset.i18n,lang); if(value) el.textContent=value; });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => { el.placeholder=t(el.dataset.i18nPlaceholder,lang); });
    document.querySelectorAll('.service-card').forEach(card => {
      const list=card.querySelector('.service-list'), heading=card.querySelector('[data-i18n$=".title"]');
      const key=heading?.dataset.i18n?.replace('.title','.items');
      if(list&&key) list.innerHTML=t(key,lang).split('|').map(item=>`<li>${item}</li>`).join('');
    });
    const footerServiceKeys=['service.pan.title','service.itr.title','service.gstreg.title','service.pf.title','trust.business'];
    document.querySelectorAll('.footer-grid>div:nth-child(3) li').forEach((el,index)=>{ if(footerServiceKeys[index]) el.textContent=t(footerServiceKeys[index],lang); });
    const footerAddress=document.querySelector('.footer-grid>div:nth-child(4) li:first-child');
    if(footerAddress) footerAddress.textContent=t('contact.address',lang);
    document.querySelectorAll('[data-lang]').forEach(btn => btn.classList.toggle('active',btn.dataset.lang===lang));
    document.dispatchEvent(new CustomEvent('languagechange',{detail:{lang}}));
  }
  function setLanguage(lang){ localStorage.setItem('heer-language',lang); applyTranslations(lang); }
  window.HeerI18n={translations,t,currentLanguage,setLanguage,applyTranslations};
})();
